#!/bin/bash
#$ -M gx26@drexel.edu
#$ -m beas
#$ -j y
#$ -cwd
#$ -P spanierPrj
#$ -pe shm 16
#$ -l h_rt=48:00:00
#$ -l m_mem_free=2G
#$ -l h_vmem=2500M
#$ -l matlab=1

. /etc/profile.d/modules.sh
module load shared
module load sge/univa
module load proteus
module load matlab/R2015b
     
matlab -nodisplay -nodesktop -nosplash -noFigureWindows -r Main
